#!/bin/bash
if [ ! -e /opt/bosun/data/bosun.conf ]
then 
    echo "=========FIRST RUN========"
    mkdir -p /opt/bosun/data/
    cp /opt/bosun/bosun.conf.sample /opt/bosun/data/bosun.conf
fi

for i in /var/run/s6/container_environment/*
do
    export $(basename $i)=$(cat $i)
done

/opt/bosun/bosun -c /opt/bosun/data/bosun.conf

